### PR TITLE
Add support for OSX x86_64 syscalls

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Apple does not have real support for static binaries, so we have to at least link to System.dylib.

**Comment by lunixbochs** [comment]
Thanks for this! Do you mind rebasing to combine the commits? Just do a `git rebase -i HEAD~3` and change the second commit to a fixup with `f`, then force push and it will show up here.

**Comment by lunixbochs** [comment]
Nevermind, I took care of it with 3e747250ebff7ac604740ea94196d1b758d03631. Thanks again!

**Comment by ghost** [comment]
Hey - sorry to bug you, but I actually submitted that under my work email instead of my personal one which is sort of something not encouraged (was copying over my git config and must have forgotten to change it back =) ) - is there any chance I could maybe ask you to amend it to set the author to travis.mcarthur@gmail.com? Sorry to bother!

On an unrelated note - if you're interested, I may also add ARM support for Linux/OSX if you're cool with that.

**Comment by ghost** [comment]
Looks good now - so either github corrected it or you did - either way thanks :).

**Comment by lunixbochs** [comment]
That was me with a force push.

I'd love ARM support, but you should probably wait for my next commit (which restructures syscall.c to reduce code duplication and add checks/support for 32/64-bit)

**Comment by ghost** [comment]
Awesome - much appreciated and thanks :).

And no worries - I'll hold off until I see next commit - I was kind of thinking same thing would be in order at some point - thanks again!

**Pull request closed without merging**
